### ISSUE TITLE
Segfault in peg_rule

### ISSUE THREAD

**Issue by leahneukirchen** [janet-lang/janet#300]
Minimal program to reproduce on master = f9e9c70b6ce:
```
(peg/match '{:main (replace "S" {"S" :spade})} "S7")
```

```
(gdb) bt
#0  0x0000000000433c81 in peg_rule (s=s@entry=0x7fffffffde00, rule=0x4d6c50, 
    text=<optimized out>, text@entry=0x4732d8 "S7") at src/core/peg.c:379
#1  0x0000000000433f10 in cfun_peg_match (argc=2, argv=0x487480)
    at src/core/peg.c:1293
#2  0x0000000000429fba in run_vm (fiber=fiber@entry=0x471570, in=...)
    at src/core/vm.c:937
#3  0x000000000042b81f in janet_continue (fiber=fiber@entry=0x471570, in=..., 
    out=out@entry=0x7fffffffe128) at src/core/vm.c:1311
#4  0x0000000000428db4 in run_vm (fiber=fiber@entry=0x4873e0, in=...)
    at src/core/vm.c:998
#5  0x000000000042b81f in janet_continue (fiber=fiber@entry=0x4873e0, in=..., 
    out=out@entry=0x7fffffffe348) at src/core/vm.c:1311
#6  0x0000000000406947 in main (argc=<optimized out>, argv=0x7fffffffe478)
    at build/shell.c:875

(gdb) p s->captures->data
$4 = (Janet *) 0x0
```

(It works with `(replace (capture "S") ...)`.)

**Comment by bakpakin** [comment]
Fixed, thanks for this catch!
