### ISSUE TITLE
Segfault in janetc_while

### ISSUE THREAD

**Issue by seb-sec** [janet-lang/janet#407]
Steps to reproduce:
```
make
cd build/
./janet
janet:1:> (while 1 (defmacro "a" ()))
segmentation fault (core dumped)
```

Reproduced with ASAN enabled for additional details:
```
CC=gcc CFLAGS="-fsanitize=address -g -fno-omit-frame-pointer" make
cd build/
./janet
janet:1:> (while 1 (defmacro "a" ()))
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2002690==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000046d5d4 bp 0x7ffe758943d0 sp 0x7ffe758940b0 T0)
==2002690==The signal is caused by a READ memory access.
==2002690==Hint: address points to the zero page.
    #0 0x46d5d3 in janetc_while src/core/specials.c:628
    #1 0x468751 in janetc_value src/core/compile.c:647
    #2 0x46c2cc in janet_compile src/core/compile.c:814
    #3 0x46c74a in cfun src/core/compile.c:842
    #4 0x46218c in run_vm src/core/vm.c:947
    #5 0x467649 in janet_continue_no_check src/core/vm.c:1334
    #6 0x45ec00 in run_vm src/core/vm.c:1012
    #7 0x467649 in janet_continue_no_check src/core/vm.c:1334
    #8 0x408dfb in main build/shell.c:1013
    #9 0x7f13841cc1a2 in __libc_start_main ../csu/libc-start.c:308
    #10 0x408f2d in _start (/tmp/janet/build/janet+0x408f2d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/core/specials.c:628 in janetc_while
==2002690==ABORTING
```

The crash was also reproduced with clang. Compiler versions:
```
gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)
clang version 9.0.1 (Fedora 9.0.1-2.fc31)
```

Host OS is Linux, Fedora 31.
```
uname -r
5.5.8-200.fc31.x86_64
```

**Comment by pepe** [comment]
I can confirm this code (however wrong it is :-)) segfaults for me too.

**Comment by bakpakin** [comment]
Thanks for reporting, this was basically a NULL pointer dereference (NULL pointer in this case just means empty buffer), so we just check that the pointers are not NULL.
