### ISSUE TITLE
Potential out of bounds memcpy in janetc_pop_funcdef

### ISSUE THREAD

**Issue by seb-sec** [janet-lang/janet#409]
Steps to reproduce:
Compiler optimization level was set to -O0 in the Makefile to prevent some variable values being optimized out in the gdb debugging session. Compile with ASAN enabled:
```
CC=gcc CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" make
cd build
./janet
janet:1:> (defn ;;;;;;;;;;;;;;;;;;;;;;||||||||||! (def tab @{}) | tab)
=================================================================
==3793326==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000024d8 at pc 0x7ffff76025d0 bp 0x7fffffffb920 sp 0x7fffffffb0c8
READ of size 12 at 0x6020000024d8 thread T0
    #0 0x7ffff76025cf  (/lib64/libasan.so.5+0x9b5cf)
    #1 0x425433 in janetc_pop_funcdef src/core/compile.c:758
    #2 0x47ad4b in janetc_fn src/core/specials.c:818
    #3 0x4236e3 in janetc_value src/core/compile.c:647
    #4 0x4748c1 in dohead src/core/specials.c:269
    #5 0x475aa9 in janetc_def src/core/specials.c:349
    #6 0x4236e3 in janetc_value src/core/compile.c:647
    #7 0x425b22 in janet_compile src/core/compile.c:814
    #8 0x426003 in cfun src/core/compile.c:842
    #9 0x4a0fca in run_vm src/core/vm.c:947
    #10 0x4a59da in janet_continue_no_check src/core/vm.c:1334
    #11 0x4a20ba in run_vm src/core/vm.c:1012
    #12 0x4a59da in janet_continue_no_check src/core/vm.c:1334
    #13 0x4a5c20 in janet_continue src/core/vm.c:1357
	#14 0x4adcf4 in main build/shell.c:1013
    #15 0x7ffff724b1a2 in __libc_start_main ../csu/libc-start.c:308
    #16 0x408b0d in _start (/home/seb/stuff/fuzzing/janet/build/janet+0x408b0d)

0x6020000024d8 is located 0 bytes to the right of 8-byte region [0x6020000024d0,0x6020000024d8)
allocated by thread T0 here:
    #0 0x7ffff767514e in realloc (/lib64/libasan.so.5+0x10e14e)
    #1 0x46f739 in pushchunk src/core/regalloc.c:90
    #2 0x46f8ec in janetc_regalloc_touch src/core/regalloc.c:104
    #3 0x41e76e in janetc_resolve src/core/compile.c:243
    #4 0x423e47 in janetc_value src/core/compile.c:668
    #5 0x47acd6 in janetc_fn src/core/specials.c:811
    #6 0x4236e3 in janetc_value src/core/compile.c:647
    #7 0x47acd6 in janetc_fn src/core/specials.c:811
    #8 0x4236e3 in janetc_value src/core/compile.c:647
    #9 0x4748c1 in dohead src/core/specials.c:269
    #10 0x475aa9 in janetc_def src/core/specials.c:349
    #11 0x4236e3 in janetc_value src/core/compile.c:647
    #12 0x425b22 in janet_compile src/core/compile.c:814
    #13 0x426003 in cfun src/core/compile.c:842
    #14 0x4a0fca in run_vm src/core/vm.c:947
    #15 0x4a59da in janet_continue_no_check src/core/vm.c:1334
    #16 0x4a20ba in run_vm src/core/vm.c:1012
    #17 0x4a59da in janet_continue_no_check src/core/vm.c:1334
    #18 0x4a5c20 in janet_continue src/core/vm.c:1357
    #19 0x4adcf4 in main build/shell.c:1013
	#20 0x7ffff724b1a2 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.5+0x9b5cf)
Shadow bytes around the buggy address:
  0x0c047fff8440: fa fa 00 00 fa fa 00 fa fa fa 00 00 fa fa 00 fa
  0x0c047fff8450: fa fa 00 fa fa fa 00 fa fa fa 00 00 fa fa 00 00
  0x0c047fff8460: fa fa 00 fa fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff8470: fa fa fd fa fa fa fd fa fa fa 06 fa fa fa fd fd
  0x0c047fff8480: fa fa 00 00 fa fa fd fa fa fa fd fa fa fa 00 00
=>0x0c047fff8490: fa fa fd fa fa fa 01 fa fa fa 00[fa]fa fa fd fa
  0x0c047fff84a0: fa fa 04 fa fa fa 00 fa fa fa 00 00 fa fa 00 fa
  0x0c047fff84b0: fa fa 00 04 fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff84c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff84d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff84e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3793326==ABORTING
```

Inspection with gdb:
```
gdb janet
(gdb) b compile.c:758
Breakpoint 1 at 0x4253eb: file src/core/compile.c, line 758.
(gdb) r
janet:1:> (defn ;;;;;;;;;;;;;;;;;;;;;;||||||||||! (def tab @{}) | tab)

Breakpoint 1, janetc_pop_funcdef (c=0x7fffffffc590) at src/core/compile.c:758
758             memcpy(chunks, scope->ua.chunks, sizeof(uint32_t) * numchunks);
(gdb) p/d numchunks
$1 = 3
(gdb) p/d scope->ua.count
$2 = 1
(gdb) p/d scope->ua.capacity
$3 = 2
```

From the variable values above it seems that memory is being copied from past the bounds of `scope->ua.chunks`

This behavior was also reproduced with clang.

Compiler versions:
```
gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)
clang version 9.0.1 (Fedora 9.0.1-2.fc31)
```

System information:
Fedora 31 Workstation x86_64
```
uname -r
5.5.8-200.fc31.x86_64
```

Additional information:
The input was found with the [afl++](https://aflplus.plus/) fuzzer

**Comment by bakpakin** [comment]
Thanks for reporting this, should be fixed now.
