### ISSUE TITLE
1.9.1 segfaults on low-spec ARMv5 system (NSLU2)

### ISSUE THREAD

**Issue by cellularmitosis** [janet-lang/janet#421]
Thank you so much for working on Janet!

Janet 1.9.1 segfaults on an NSLU2 (ARMv5, 32MB RAM) running Linux.  This is a regression, as 1.8.1 works correctly.

Note that 1.9.1 runs fine on an ARMv5 system with 128MB of RAM (Pogoplug).

Here is an excerpt from `strace` output:

```
# strace ./build/janet
...
set_robust_list(0xb6c94070, 12)         = 0
rt_sigaction(SIGRTMIN, {0xb6e16550, [], SA_RESTORER|SA_SIGINFO, 0xb6ccdd50}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0xb6e163e4, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0xb6ccdd50}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
brk(0)                                  = 0x946000
brk(0x968000)                           = 0x968000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0xb6ca3500} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

Here is a similar excerpt from 1.8.1, which does not crash:

```
set_robust_list(0xb6c43070, 12)         = 0
rt_sigaction(SIGRTMIN, {0xb6dbe550, [], SA_RESTORER|SA_SIGINFO, 0xb6c75d50}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0xb6dbe3e4, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0xb6c75d50}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
brk(0)                                  = 0xb7f9b000
brk(0xb7fbd000)                         = 0xb7fbd000
brk(0xb7fde000)                         = 0xb7fde000
brk(0xb7fff000)                         = 0xb7fff000
brk(0xb8020000)                         = 0xb8020000
fstat64(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6ec0000
write(1, "Janet 1.8.1-local  Copyright (C)"..., 55Janet 1.8.1-local  Copyright (C) 2017-2020 Calvin Rose
) = 55
```

**Comment by cellularmitosis** [comment]
The segfault does not happen with `-O0`.

I rebuilt with `-Os -g`, here's the backtrace:

```
Reading symbols from ./build/janet...done.
(gdb) run
Starting program: /root/tmp/janet-1.9.1-Os/build/janet 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabi/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
janet_rng_seed (rng=0xb6d87500, seed=seed@entry=0) at src/core/math.c:71
71          rng->a = seed;
(gdb) bt
#0  janet_rng_seed (rng=0xb6d87500, seed=seed@entry=0) at src/core/math.c:71
#1  0x0001d2f0 in janet_init () at src/core/vm.c:1423
#2  0x000159a8 in main (argc=1, argv=0xbefffd94) at build/shell.c:989
(gdb) 
```

**Comment by cellularmitosis** [comment]
gcc on the crashing machine:

```
# gcc --version
gcc (Debian 4.9.2-10+deb8u2) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

gcc on the other ARMv5 box which doesn't crash:

```
# gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by cellularmitosis** [comment]
Starting to think this has nothing to do with the source code, so closing.
